name: wick_apps
description: "Wick Apps frontend library."
version: 0.0.1

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  http: ^1.2.1
  shared_preferences: ^2.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
